name: Docker image build and publish 2 - private ECR repo
on:
#   workflow_dispatch:
  workflow_call:
    inputs:
      path_to_dockerfile:
        description: Path to the dockerfile (default = 'Dockerfile')
        default: "Dockerfile"
        type: string
      docker_build_dir:
        description: Docker build directory (default = '.')
        default: "."
        type: string
      image_tag:
        description: Tag to apply to images.
        type: string
        default: ${{ github.sha }}
      aws_account_id:
        description: AWS Account ID
        type: string
      ecr_repo_name:
        description: ECR repository name (default = lowercase of the GitHub repository name with / replaced by _ )
        required: false
        type: string

concurrency: ci-${{ github.repository }}-docker-pipeline
        
jobs:
  docker:
    runs-on:
      - codebuild-KenFirebreakCodeBuild2-${{ github.run_id }}-${{ github.run_attempt }}
        image:arm-3.0

    permissions:
      id-token: write
      contents: read

    outputs:
      image_tag: ${{ steps.build-publish.outputs.image_tag }}
      full_image: ${{ steps.build-publish.outputs.full_image }}

    steps:
    #   - uses: actions/checkout@v3
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ inputs.image_tag }}
          show-progress: false

      - name: Login to Amazon ECR
        id: login-ecr
        shell: bash
        run: aws ecr get-login-password --region "$AWS_DEFAULT_REGION" | docker login --username AWS --password-stdin "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"

      - name: Build, tag, and push image to Amazon ECR
        id: build-publish
        shell: bash
        env:
          ECR_REPOSITORY: "${{ inputs.ecr_repo_name || github.event.repository.name }}"
          IMAGE_TAG: ${{ inputs.image_tag }}
        run: |
          docker build "${{ inputs.docker_build_dir }}" -f "${{ inputs.path_to_dockerfile }}" -t "$IMAGE_REPO_NAME_BASE/$ECR_REPOSITORY:$IMAGE_TAG"
          docker push "$IMAGE_REPO_NAME_BASE/$ECR_REPOSITORY:$IMAGE_TAG"
          echo "IMAGE $IMAGE_TAG is pushed to $IMAGE_REPO_NAME_BASE/$ECR_REPOSITORY"
          echo "image_tag=$IMAGE_TAG" 
          echo "full_image=$IMAGE_REPO_NAME_BASE/$ECR_REPOSITORY:$IMAGE_TAG"
